"""small update

Revision ID: ed292dd9c78a
Revises: 3fd9c8e4e636
Create Date: 2025-10-16 10:38:59.413039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed292dd9c78a'
down_revision = '3fd9c8e4e636'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('city')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city', sa.VARCHAR(length=50), nullable=True))

    # ### end Alembic commands ###
